### ISSUE TITLE
Intro Math

### ISSUE THREAD

**Issue by chipbell4** [MercerBinaryBears/Slides#4]
- Calculating Primes
- GCD
- Basic Geometry
- Fractions
- Complex Numbers

**Comment by chipbell4** [comment]
Maybe fraction class discussion?

**Comment by tylerburnham42** [comment]
Add this stuff
https://www.topcoder.com/community/data-science/data-science-tutorials/mathematics-for-topcoders/

**Comment by tylerburnham42** [comment]
Fractions and Complex Numbers remain
